name: myrepo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          - aarch64_generic
          - x86_64
          
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install usign
      run: |
        git clone https://git.kejizero.online/zhao/usign
        cd usign
        mkdir build && cd build && cmake .. && make && sudo make install

    - name: Download index file
      run: | 
        wget -O ipkg-make-index.sh https://raw.githubusercontent.com/zhiern/ipkg-make-index/refs/heads/main/ipkg-make-index.sh
        chmod +x ipkg-make-index.sh

    - name: Download plugin
      run: | 
        if [ "${{ matrix.target }}" = "aarch64_generic" ]; then
            current_date=$(date +%Y%m%d)
            mkdir -p "$current_date" && 
            wget -O - https://github.com/zhiern/openwrt-package/releases/download/openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C $current_date
            wget -O - https://github.com/zhiern/openwrt-package/releases/download/Helloworld-openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C $current_date
            wget -O - https://github.com/zhiern/openwrt-package/releases/download/linkease-openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C $current_date
        elif [ "${{ matrix.target }}" = "x86_64" ]; then
            current_date=$(date +%Y%m%d)
            mkdir -p "$current_date" && 
            wget -O - https://github.com/zhiern/openwrt-package/releases/download/openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C $current_date
            wget -O - https://github.com/zhiern/openwrt-package/releases/download/Helloworld-openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C $current_date
            wget -O - https://github.com/zhiern/openwrt-package/releases/download/linkease-openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C $current_date
        fi

    - name: Perform indexing operations
      run: |
        wget -O key.tar.gz "https://github.com/zhiern/ZeroWrt/raw/refs/heads/openwrt-24.10/openwrt/patch/key.tar.gz"
        wget -O mkhash "https://github.com/zhiern/Extras-ipk/releases/download/mkhash/mkhash"
        tar -xzvf key.tar.gz
        sed -i 's|export PATH="$TOP/staging_dir/host/bin:$PATH"|export PATH="$(pwd):$PATH"|' kmod-sign
        bash kmod-sign $current_date
        
    - name: Git push
      continue-on-error: true
      run: |
        git config --local user.name "zhiern"
        git config --local user.email "2519840456@qq.com"
        [ -d .git ] && git init
        git add --all
        git commit -sm "$current_date"
        git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${{ matrix.target }}
