name: myrepo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          - aarch64_generic
          - x86_64
          
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install usign
      run: |
        git clone https://git.kejizero.online/zhao/usign
        cd usign
        mkdir build && cd build && cmake .. && make && sudo make install

    - name: Download index file
      run: | 
        wget -O ipkg-make-index.sh https://raw.githubusercontent.com/zhiern/ipkg-make-index/refs/heads/main/ipkg-make-index.sh
        chmod +x ipkg-make-index.sh

    - name: Download plugin
      run: | 
        if [ "${{ matrix.target }}" = "aarch64_generic" ]; then
        mkdir -p myrepo && wget -O - https://github.com/zhiern/openwrt-package/releases/download/openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/Helloworld-openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/linkease-openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C myrepo
        elif [ "${{ matrix.target }}" = "x86_64" ]; then
        mkdir -p myrepo && wget -O - https://github.com/zhiern/openwrt-package/releases/download/openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/Helloworld-openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/linkease-openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C myrepo
        fi
        wget -O myrepo/my-private.key https://raw.githubusercontent.com/zhiern/ipkg-make-index/refs/heads/main/my-private.key
        wget -O myrepo/my-private.key.pub https://raw.githubusercontent.com/zhiern/ipkg-make-index/refs/heads/main/my-private.key.pub

    - name: Perform indexing operations
      run: |
        ./ipkg-make-index.sh myrepo > myrepo/Packages
        cd myrepo
        usign -S -m Packages -s my-private.key
        gzip -9nc Packages > Packages.gz
        cd ..
        rm -rf ipkg-make-index.sh
        rm -rf usign

    - name: Git push
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        mkdir push-dir
        mkdir -p push-dir/myrepo
        cp -r myrepo/* push-dir/myrepo/
        cd push-dir
        git init
        git checkout -b ${{ matrix.target }}
        git add .
        git commit -m "更新插件版本"
        git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" ${{ matrix.target }}
