name: myrepo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          - aarch64_generic
          - x86_64
          
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download plugin
      run: | 
        if [ "${{ matrix.target }}" = "aarch64_generic" ]; then
        mkdir -p myrepo && wget -O - https://github.com/zhiern/openwrt-package/releases/download/openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/Helloworld-openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/linkease-openwrt-24.10-aarch64_generic/aarch64_generic.tar.gz | tar -xz -C myrepo
        elif [ "${{ matrix.target }}" = "x86_64" ]; then
        mkdir -p myrepo && wget -O - https://github.com/zhiern/openwrt-package/releases/download/openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/Helloworld-openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C myrepo
        wget -O - https://github.com/zhiern/openwrt-package/releases/download/linkease-openwrt-24.10-x86_64/x86_64.tar.gz | tar -xz -C myrepo
        fi

    - name: Perform indexing operations
      run: |
        wget -O key.tar.gz "https://github.com/zhiern/ZeroWrt/raw/refs/heads/openwrt-24.10/openwrt/patch/key.tar.gz"
        wget -O mkhash "https://github.com/zhiern/Extras-ipk/releases/download/mkhash/mkhash"
        chmod - R 777 mkhash
        tar -xzvf key.tar.gz
        sed -i 's|export PATH="$TOP/staging_dir/host/bin:$PATH"|export PATH="$(pwd):$PATH"|' kmod-sign
        bash kmod-sign myrepo
        
    - name: Upload OTA File to FTP
      uses: zhiern/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.ftp_address }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: opkg/openwrt-24.10/${{ matrix.target }}/
        local-dir: myrepo/
        dangerous-clean-slate: true
